### PR TITLE
AMM: rpc method removal

### PR DESCRIPTION
**Pull request by enthusiastmartin**
Removed rpc methods -  get spot/sell/buy price - as they are no longer needed.

### CODE REVIEW

**Comment by jak-pan** [comment]
I'll approve this but don't merge this yet. We use it in UI and the WASM math lib is to be implemented, so we don't break the compatibility with latest node.

**Review by jak-pan — APPROVED** [review]

**Comment by jak-pan** [comment]
Can be merged after https://github.com/galacticcouncil/hack.HydraDX-app/issues/10

**Comment by enthusiastmartin** [comment]
bench test comment ( ignore )

**Comment by jak-pan** [comment]
Can merge after merging master

**Comment by enthusiastmartin** [comment]
I wonder if at this point  it is not easier to remove it again instead of
merging master. I'll have a look what would be easier.

**Comment by jak-pan** [comment]
Looks like very easy resolve

**Pull request merged**
