### PR TITLE
Bench Tool Update

### PR DESCRIPTION
**Pull request by enthusiastmartin**
- [x] Create storage heavy benchmark (can be inspired by actual substrate benchmark)
- [ ] Dump bench details after failed benchmark
- [x] Rerun once if some failed and some ok
- [ ] Automatic weight update on benchbot run
- [x] Weights update

### CODE REVIEW

**Comment by enthusiastmartin** [comment]
@jak-pan  to quickly resolve #127  - I suggest to merge this one so the weighs and ref are synced. And people can rerun the tests. Lumir is also running his test again. 

I'll do the outstanding work on the tool in new PR.

**Review by jak-pan — APPROVED** [review]

**Review by jak-pan — COMMENTED** [review]
On the other hand. We could just pick the .json to partially fix for now and merge rest later?

**Comment by jak-pan** [comment]
But if you are happy with the state now we can merge

**Comment by enthusiastmartin** [comment]
Yes, current state is fine. I'll merge and do rest as other PR.

**Pull request merged**
