### PR TITLE
Exchange benchmark update

### PR DESCRIPTION
**Pull request by enthusiastmartin**
Use predefined list of amounts instead of randomly generating one each benchmark.

### CODE REVIEW

**Review by jak-pan — APPROVED** [review]

**Comment by jak-pan** [comment]
Do we have some good news regarding the consistency? :)

**Comment by jak-pan** [comment]
Re-bench?

**Comment by enthusiastmartin** [comment]
> Re-bench?

Done in  the #119

**Comment by jak-pan** [comment]
I meant re-run benchmarks now that it's fixed.

**Comment by enthusiastmartin** [comment]
> I meant re-run benchmarks now that it's fixed.

ahyes.in progress. lumir will run his test again this night.

i did multiple runs on bech machine and all consistenly around the ref value.

**Pull request merged**
