### PR TITLE
fix!: WithFee::with_fee method

### PR DESCRIPTION
**Pull request by Roznovjak**
## Description
fix WithFee::with_fee() method and also add without_fee() method.

https://github.com/galacticcouncil/HydraDX-node/blob/694cce69ee44890dcbd05c9ef1cd83079e3ce1ac/primitives/src/lib.rs#L121-L124

The current implementation computes `value * (100% - fee_percentage)` instead of `value + fee`

### CODE REVIEW

**Review by enthusiastmartin — COMMENTED** [review]
looks ok to me. but i am not very convinced that we need to update all versions of all pallets and runtime too. 

I would just update the primitives crate version.

**Comment by Roznovjak** [comment]
What do you think @jak-pan ? It is a breaking change, but the affected method was never used before in the code( at least not in this repository).

**Comment by jak-pan** [comment]
Just runtime and impl_version in runtime. Where else is this used?

**Comment by Roznovjak** [comment]
We don't use `with_fee()` in our node repositories. We also need `without_fee` method in LBP so I have implemented it. I am not sure if I answered your question.

**Comment by jak-pan** [comment]
Only runtime then.

**Comment by Roznovjak** [comment]
I have reverted impl_runtime version to the previous one. The only version changes are now in `primitives` and `runtime` package.

**Review by enthusiastmartin — APPROVED** [review]

**Pull request merged**
